version: "3.3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node-modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=hamid
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
      - S3_ENDPOINT=https://s3.ir-thr-at1.arvanstorage.com
      - S3_ACCESS_KEY_ID=
      - S3_SECRET_ACCESS_KEY=
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hamid
      - MONGO_INITDB_ROOT_PASSWORD=mypassword