version: "3.3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hamid
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
  emqx:
    image: emqx/emqx:v4.0.0
    restart: always
    environment:
      EMQX_NAME: foo_emqx
      EMQX_HOST: 127.0.0.1
      EMQX_BACKEND_REDIS_POOL1__SERVER: 127.0.0.1:6379
    ports:
      - "18083:18083"
      - "1883:1883"
      - "4369:4369"
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
    environment:
      - INFLUX_TOKEN=NSmf7GJCt7xtvQJUagpkAsL8_dFF0ANFZr2A2vVeeA_kWxifvFob9soDs3jlTqN-lUfdZFgNsSojucICgRbbGg==
  telegraf:
    image: telegraf
    configs:
      - source: telegraf-conf
        target: /etc/telegraf/telegraf.conf
    ports:
      - 8186:8186
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
  kapacitor:
    image: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  chronograf:
    image: chronograf:latest
    volumes:
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
configs:
  telegraf-conf:
    file: ./telegraf.conf
volumes:
  mongo-db:
  vol-emqx-data:
  vol-emqx-etc:
  vol-emqx-log:
